package rollpoker

var ALL_NOUNS []string;

func init() {
	ALL_NOUNS = []string{
"Ability", "Abroad", "Abuse", "Access", "Accident", "Account", "Action",
"Active", "Activity", "Actor", "Addition", "Address", "Administration",
"Adult", "Advance", "Advantage", "Advertising", "Advice", "Affair", "Affect",
"Afternoon", "Agency", "Agent", "Agreement", "Airline", "Airport", "Alarm",
"Alcohol", "Alternative", "Ambition", "Amount", "Analysis", "Analyst", "Anger",
"Angle", "Animal", "Annual", "Answer", "Anxiety", "Anybody", "Anything",
"Anywhere", "Apartment", "Appeal", "Appearance", "Apple", "Application",
"Appointment", "Area", "Argument", "Army", "Arrival", "Article", "Aside",
"Aspect", "Assignment", "Assist", "Assistance", "Assistant", "Associate",
"Association", "Assumption", "Atmosphere", "Attack", "Attempt", "Attention",
"Attitude", "Audience", "Author", "Average", "Award", "Awareness", "Baby",
"Back", "Background", "Bake", "Balance", "Ball", "Band", "Bank", "Base",
"Baseball", "Basis", "Basket", "Bath", "Bathroom", "Battle", "Beach", "Bear",
"Beat", "Beautiful", "Bedroom", "Beer", "Beginning", "Being", "Bell", "Belt",
"Bench", "Bend", "Benefit", "Beyond", "Bicycle", "Bike", "Bill", "Bird",
"Birth", "Birthday", "Bite", "Bitter", "Black", "Blame", "Blank", "Blind",
"Block", "Blood", "Blow", "Blue", "Board", "Boat", "Body", "Bone", "Bonus",
"Book", "Boot", "Border", "Boss", "Bother", "Bottle", "Bottom", "Bowl",
"Boyfriend", "Brain", "Branch", "Brave", "Bread", "Break", "Breakfast",
"Breast", "Breath", "Brick", "Bridge", "Brief", "Brilliant", "Broad",
"Brother", "Brown", "Brush", "Buddy", "Budget", "Building", "Bunch", "Burn",
"Business", "Button", "Buyer", "Cabinet", "Cable", "Cake", "Calendar", "Call",
"Calm", "Camera", "Camp", "Campaign", "Cancel", "Cancer", "Candidate",
"Candle", "Candy", "Capital", "Card", "Care", "Career", "Carpet", "Carry",
"Case", "Cash", "Catch", "Category", "Cause", "Celebration", "Cell", "Chain",
"Chair", "Challenge", "Champion", "Championship", "Chance", "Change",
"Channel", "Chapter", "Character", "Charge", "Charity", "Chart", "Check",
"Cheek", "Chemical", "Chemistry", "Chest", "Chicken", "Child", "Childhood",
"Chip", "Chocolate", "Choice", "Church", "Cigarette", "City", "Claim", "Class",
"Classic", "Classroom", "Clerk", "Click", "Client", "Climate", "Clock",
"Closet", "Clothes", "Cloud", "Club", "Clue", "Coach", "Coast", "Coat", "Code",
"Coffee", "Cold", "Collar", "Collection", "College", "Combination", "Combine",
"Comfort", "Comfortable", "Command", "Comment", "Commercial", "Commission",
"Committee", "Common", "Communication", "Community", "Company", "Comparison",
"Competition", "Complaint", "Complex", "Computer", "Concentrate", "Concept",
"Concern", "Concert", "Conclusion", "Condition", "Conference", "Confidence",
"Conflict", "Confusion", "Connection", "Consequence", "Consideration",
"Consist", "Constant", "Construction", "Contact", "Contest", "Context",
"Contract", "Contribution", "Control", "Conversation", "Convert", "Cook",
"Cookie", "Copy", "Corner", "Cost", "Count", "Counter", "Country", "County",
"Couple", "Courage", "Course", "Court", "Cousin", "Cover", "Crack", "Craft",
"Crash", "Crazy", "Cream", "Creative", "Credit", "Crew", "Criticism", "Cross",
"Culture", "Currency", "Current", "Curve", "Customer", "Cycle", "Damage",
"Dance", "Dare", "Dark", "Data", "Database", "Date", "Daughter", "Dead",
"Deal", "Dealer", "Dear", "Death", "Debate", "Debt", "Decision", "Deep",
"Definition", "Degree", "Delay", "Delivery", "Demand", "Department",
"Departure", "Dependent", "Deposit", "Depression", "Depth", "Description",
"Design", "Designer", "Desire", "Desk", "Detail", "Development", "Device",
"Devil", "Diamond", "Diet", "Difference", "Difficulty", "Dimension", "Dinner",
"Direction", "Director", "Dirt", "Disaster", "Discipline", "Discount",
"Discussion", "Disease", "Dish", "Disk", "Display", "Distance", "Distribution",
"District", "Divide", "Doctor", "Document", "Door", "Double", "Doubt", "Draft",
"Drag", "Drama", "Draw", "Drawer", "Drawing", "Dream", "Dress", "Drink",
"Drive", "Driver", "Drop", "Drunk", "Dump", "Dust", "Duty", "Earth", "Ease",
"East", "Economics", "Economy", "Edge", "Editor", "Education", "Effect",
"Effective", "Efficiency", "Effort", "Election", "Elevator", "Emergency",
"Emotion", "Emphasis", "Employ", "Employee", "Employer", "Employment",
"Energy", "Engine", "Engineer", "Engineering", "Entertainment", "Enthusiasm",
"Entrance", "Entry", "Environment", "Equal", "Equipment", "Equivalent",
"Error", "Escape", "Essay", "Establishment", "Estate", "Estimate", "Evening",
"Event", "Evidence", "Exam", "Examination", "Example", "Exchange",
"Excitement", "Excuse", "Exercise", "Exit", "Experience", "Expert",
"Explanation", "Expression", "Extension", "Extent", "External", "Extreme",
"Face", "Fact", "Factor", "Fail", "Failure", "Fall", "Familiar", "Family",
"Farm", "Farmer", "Father", "Fault", "Fear", "Feature", "Feed", "Feedback",
"Feel", "Feeling", "Female", "Field", "Fight", "Figure", "File", "Fill",
"Film", "Final", "Finance", "Finding", "Finger", "Finish", "Fire", "Fish",
"Fishing", "Flight", "Floor", "Flow", "Flower", "Focus", "Fold", "Following",
"Food", "Foot", "Football", "Force", "Forever", "Form", "Formal", "Fortune",
"Foundation", "Frame", "Freedom", "Friend", "Friendship", "Front", "Fruit",
"Fuel", "Function", "Funeral", "Funny", "Future", "Gain", "Game", "Garage",
"Garbage", "Garden", "Gate", "Gather", "Gear", "Gene", "General", "Gift",
"Girl", "Girlfriend", "Give", "Glad", "Glass", "Glove", "Goal", "Gold", "Golf",
"Good", "Government", "Grab", "Grade", "Grand", "Grandfather", "Grandmother",
"Grass", "Great", "Green", "Grocery", "Ground", "Group", "Growth", "Guarantee",
"Guard", "Guess", "Guest", "Guidance", "Guide", "Guitar", "Habit", "Hair",
"Half", "Hall", "Hand", "Handle", "Hang", "Harm", "Hate", "Head", "Health",
"Hearing", "Heart", "Heat", "Heavy", "Height", "Hell", "Hello", "Help", "Hide",
"High", "Highlight", "Highway", "Hire", "Historian", "History", "Hold", "Hole",
"Holiday", "Home", "Homework", "Honey", "Hook", "Hope", "Horror", "Horse",
"Hospital", "Host", "Hotel", "Hour", "House", "Housing", "Human", "Hunt",
"Hurry", "Hurt", "Husband", "Idea", "Ideal", "Illegal", "Image", "Imagination",
"Impact", "Implement", "Importance", "Impress", "Impression", "Improvement",
"Incident", "Income", "Increase", "Independence", "Independent", "Indication",
"Individual", "Industry", "Inevitable", "Inflation", "Influence",
"Information", "Initial", "Initiative", "Injury", "Insect", "Inside",
"Inspection", "Inspector", "Instance", "Instruction", "Insurance", "Intention",
"Interaction", "Interest", "Internal", "International", "Internet",
"Interview", "Introduction", "Investment", "Invite", "Iron", "Island", "Issue",
"Item", "Jacket", "Join", "Joint", "Joke", "Judge", "Judgment", "Juice",
"Jump", "Junior", "Jury", "Keep", "Kick", "Kill", "Kind", "King", "Kiss",
"Kitchen", "Knee", "Knife", "Knowledge", "Lack", "Ladder", "Lady", "Lake",
"Land", "Landscape", "Language", "Laugh", "Lawyer", "Layer", "Lead", "Leader",
"Leadership", "Leading", "League", "Leather", "Leave", "Lecture", "Length",
"Lesson", "Letter", "Level", "Library", "Life", "Lift", "Light", "Limit",
"Line", "Link", "List", "Listen", "Literature", "Living", "Load", "Loan",
"Local", "Location", "Lock", "Long", "Look", "Loss", "Love", "Luck", "Lunch",
"Machine", "Magazine", "Mail", "Main", "Maintenance", "Major", "Make", "Male",
"Mall", "Management", "Manager", "Manner", "Manufacturer", "Many", "March",
"Mark", "Market", "Marketing", "Marriage", "Master", "Match", "Mate",
"Material", "Math", "Matter", "Maximum", "Maybe", "Meal", "Meaning",
"Measurement", "Meat", "Media", "Medicine", "Medium", "Meet", "Meeting",
"Member", "Membership", "Memory", "Mention", "Menu", "Mess", "Message",
"Metal", "Method", "Middle", "Midnight", "Might", "Milk", "Mind", "Mine",
"Minimum", "Minor", "Minute", "Mirror", "Miss", "Mission", "Mistake",
"Mixture", "Mobile", "Mode", "Model", "Moment", "Money", "Monitor", "Month",
"Mood", "Morning", "Mortgage", "Most", "Mother", "Motor", "Mountain", "Mouse",
"Mouth", "Move", "Movie", "Muscle", "Music", "Nail", "Name", "Nasty", "Nation",
"National", "Native", "Natural", "Nature", "Neat", "Necessary", "Neck",
"Negative", "Negotiation", "Nerve", "Network", "News", "Newspaper", "Night",
"Nobody", "Noise", "Normal", "North", "Nose", "Note", "Nothing", "Notice",
"Novel", "Number", "Nurse", "Object", "Objective", "Obligation", "Occasion",
"Offer", "Office", "Officer", "Official", "Opening", "Operation", "Opinion",
"Opportunity", "Opposite", "Option", "Orange", "Order", "Ordinary",
"Organization", "Original", "Other", "Outcome", "Outside", "Oven", "Owner",
"Pace", "Pack", "Package", "Page", "Pain", "Paint", "Painting", "Pair",
"Panic", "Paper", "Parent", "Park", "Parking", "Part", "Particular", "Partner",
"Party", "Pass", "Passage", "Passenger", "Passion", "Past", "Path", "Patience",
"Patient", "Pattern", "Pause", "Payment", "Peace", "Peak", "Penalty",
"Pension", "People", "Percentage", "Perception", "Performance", "Period",
"Permission", "Permit", "Person", "Personal", "Personality", "Perspective",
"Phase", "Philosophy", "Phone", "Photo", "Phrase", "Physical", "Physics",
"Piano", "Pick", "Picture", "Piece", "Pipe", "Pitch", "Pizza", "Place", "Plan",
"Plane", "Plant", "Plastic", "Plate", "Platform", "Play", "Player", "Pleasure",
"Plenty", "Poem", "Poet", "Poetry", "Point", "Police", "Policy", "Politics",
"Pollution", "Pool", "Population", "Position", "Positive", "Possession",
"Possibility", "Possible", "Post", "Potato", "Potential", "Pound", "Power",
"Practice", "Preference", "Preparation", "Presence", "Present", "Presentation",
"President", "Press", "Pressure", "Price", "Pride", "Priest", "Primary",
"Principle", "Print", "Prior", "Priority", "Private", "Prize", "Problem",
"Procedure", "Process", "Produce", "Product", "Profession", "Professional",
"Professor", "Profile", "Profit", "Program", "Progress", "Project", "Promise",
"Promotion", "Prompt", "Proof", "Property", "Proposal", "Protection",
"Psychology", "Public", "Pull", "Punch", "Purchase", "Purple", "Purpose",
"Push", "Quality", "Quantity", "Quarter", "Queen", "Question", "Quiet", "Quit",
"Quote", "Race", "Radio", "Rain", "Raise", "Range", "Rate", "Ratio", "Reach",
"Reaction", "Read", "Reading", "Reality", "Reason", "Reception", "Recipe",
"Recognition", "Recommendation", "Record", "Recording", "Recover", "Reference",
"Reflection", "Refrigerator", "Refuse", "Region", "Register", "Regret",
"Regular", "Relation", "Relationship", "Relative", "Release", "Relief",
"Remote", "Remove", "Rent", "Repair", "Repeat", "Replacement", "Reply",
"Report", "Representative", "Republic", "Reputation", "Request", "Requirement",
"Research", "Reserve", "Resident", "Resist", "Resolution", "Resolve", "Resort",
"Resource", "Respect", "Respond", "Response", "Responsibility", "Rest",
"Restaurant", "Result", "Return", "Reveal", "Revenue", "Review", "Revolution",
"Reward", "Rice", "Rich", "Ride", "Ring", "Rise", "Risk", "River", "Road",
"Rock", "Role", "Roll", "Roof", "Room", "Rope", "Rough", "Round", "Routine",
"Royal", "Ruin", "Rule", "Rush", "Safe", "Safety", "Sail", "Salad", "Salary",
"Sale", "Salt", "Sample", "Sand", "Sandwich", "Satisfaction", "Save",
"Savings", "Scale", "Scene", "Schedule", "Scheme", "School", "Science",
"Score", "Scratch", "Screen", "Screw", "Script", "Search", "Season", "Seat",
"Second", "Secret", "Secretary", "Section", "Sector", "Security", "Selection",
"Self", "Sell", "Senior", "Sense", "Sensitive", "Sentence", "Series", "Serve",
"Service", "Session", "Setting", "Shake", "Shame", "Shape", "Share", "Shelter",
"Shift", "Shine", "Ship", "Shirt", "Shock", "Shoe", "Shoot", "Shop",
"Shopping", "Shot", "Shoulder", "Show", "Shower", "Sick", "Side", "Sign",
"Signal", "Signature", "Significance", "Silly", "Silver", "Simple", "Sing",
"Singer", "Single", "Sink", "Sister", "Site", "Situation", "Size", "Skill",
"Skin", "Skirt", "Sleep", "Slice", "Slide", "Slip", "Smell", "Smile", "Smoke",
"Snow", "Society", "Sock", "Soft", "Software", "Soil", "Solid", "Solution",
"Somewhere", "Song", "Sort", "Sound", "Soup", "Source", "South", "Space",
"Spare", "Speaker", "Special", "Specialist", "Specific", "Speech", "Speed",
"Spell", "Spend", "Spirit", "Spiritual", "Spite", "Split", "Sport", "Spot",
"Spray", "Spread", "Spring", "Square", "Stable", "Staff", "Stage", "Stand",
"Standard", "Star", "Start", "State", "Statement", "Station", "Status", "Stay",
"Steak", "Steal", "Step", "Stick", "Still", "Stock", "Stomach", "Stop",
"Storage", "Store", "Storm", "Story", "Strain", "Stranger", "Strategy",
"Street", "Strength", "Stress", "Stretch", "Strike", "String", "Strip",
"Stroke", "Structure", "Struggle", "Student", "Studio", "Study", "Stuff",
"Stupid", "Style", "Subject", "Substance", "Success", "Suck", "Sugar",
"Suggestion", "Suit", "Summer", "Supermarket", "Support", "Surgery",
"Surprise", "Surround", "Survey", "Suspect", "Sweet", "Swim", "Swimming",
"Swing", "Switch", "Sympathy", "System", "Table", "Tackle", "Tale", "Talk",
"Tank", "Target", "Task", "Taste", "Teach", "Teacher", "Teaching", "Team",
"Tear", "Technology", "Telephone", "Television", "Tell", "Temperature",
"Temporary", "Tennis", "Tension", "Term", "Test", "Text", "Thanks", "Theme",
"Theory", "Thing", "Thought", "Throat", "Ticket", "Till", "Time", "Title",
"Today", "Tomorrow", "Tone", "Tongue", "Tonight", "Tool", "Tooth", "Topic",
"Total", "Touch", "Tough", "Tour", "Tourist", "Towel", "Tower", "Town",
"Track", "Trade", "Tradition", "Traffic", "Train", "Trainer", "Training",
"Transition", "Transportation", "Trash", "Travel", "Treat", "Tree", "Trick",
"Trip", "Trouble", "Truck", "Trust", "Truth", "Tune", "Turn", "Twist", "Type",
"Uncle", "Understanding", "Union", "Unique", "Unit", "University", "Upper",
"Upstairs", "User", "Usual", "Vacation", "Valuable", "Value", "Variation",
"Variety", "Vast", "Vegetable", "Vehicle", "Version", "Video", "View",
"Village", "Virus", "Visit", "Visual", "Voice", "Volume", "Wait", "Wake",
"Walk", "Wall", "Warning", "Wash", "Watch", "Water", "Wave", "Weakness",
"Wealth", "Wear", "Weather", "Wedding", "Week", "Weekend", "Weight", "Weird",
"Welcome", "West", "Western", "Wheel", "Whereas", "While", "White", "Whole",
"Wife", "Will", "Wind", "Window", "Wine", "Wing", "Winner", "Winter", "Wish",
"Witness", "Woman", "Wonder", "Wood", "Word", "Work", "Worker", "Working",
"World", "Worry", "Worth", "Wrap", "Writer", "Writing", "Yard", "Year",
"Yellow", "Yesterday", "Young", "Youth", "Zone",
}
}
